### ISSUE TITLE
Update standards page

### ISSUE THREAD

**Issue by jpmckinney** [influencemapping/influencemapping.org#2]
https://github.com/influencemapping/influencemapping.org/blob/gh-pages/standard/index.md

**Comment by miguelpaz** [comment]
awesome


2015-10-16 4:07 GMT-03:00 James McKinney <notifications@github.com>:

>
> https://github.com/influencemapping/influencemapping.org/blob/gh-pages/standard/index.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influencemapping/influencemapping.org/issues/2>.
>



-- 
Miguel Paz @miguelpaz
Nieman-Berkman Fellow 2014-2015
Poderomedia.org @poderomedia - Poderopedia.org @poderopedia
PoderomediaAcademy #PAcademy - Manual Periodismo de Datos @periodismodata
Hacks/Hackers Chile @hackshackersSCL

**Comment by jpmckinney** [comment]
I think I did the intended updates at the time in c00f0c4675b91fb8b918e4079a0b1bac
